version: "3.9"
services:
  clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickhouse_lab
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: telecom
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: redhat123

volumes:
  clickhouse_data:
  clickhouse_logs:
